# Site Settings
title: My Resume
url: 'https://jgmayworm.github.io/online-cv/'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Jose Guilherme Mayworm
tagline: Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Jose Guilherme Mayworm has a Master's Degree in Computer Science, acquired from the Post Graduate Program in Computing(PPGI) at the Federal University of Rio de Janeiro(UFRJ). 
His research is associated with distributed information dissemination towards scenarios where people move frequently and interact in brief encounters.
Has knowledge on social network analysis, data mining(text), and machine learning. 
Also has knowledge of SQL and has worked with programming languages such as Java, C ++ and JavaScript. 
Currently develops in Python and works mainly on Linux platforms.'

#sidebar links
email: jgmayworm@gmail.com
phone: +55 24 999679638
# website: blog.webjeda.com #do not add http://
linkedin: jgmayworm
github: jgmayworm
# twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
future: true
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
